#!/usr/bin/env python2.7
import os
from sys import argv
from git import Repo
import config

def main():
    # reload vagrant unless "--skip-vagrant" argument exists
    if ('--skip-vagrant' not in argv):
        os.chdir(config.tf)
        os.system("vagrant reload")


    # checkout master branch if branch is in a detached head state (caused by 'vagrant reload')
    for item in config.directoryList:
        itemRepo = Repo(item[1])
        if itemRepo.head.is_detached:
            itemRepo.git.checkout('-')
            print(item[0] + ": detached head state. Checking out " + itemRepo.active_branch.name + ".")
        else:
            print(item[0] + ": " + itemRepo.active_branch.name + " branch.")


    # copy production site config to local only if "--copy-configs" argument exists
    if ('--copy-configs' in argv):
        print('----------------')
        for file in config.siteConfigFiles:
            with open(file[0]) as f:
                with open(file[1], "w") as f1:
                    for line in f:
                        f1.write(line)
            print(os.path.basename(file[0]) + " copied to local site config.")

if __name__ == "__main__":
    main()